### PR TITLE
getxattr: move check of valid return value closer to its request

### PR DESCRIPTION
**Pull request by HereThereBeDragons**
Issue #3515 

check for the `found` was definitely done too late

 https://github.com/cvmfs/cvmfs/blob/9fc9c4015f6f3fcc98c9cec1f48fdb77003a034f/cvmfs/cvmfs.cc#L1747-L1755

hopefully also solves the assert issue

### CODE REVIEW

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
integration test `Testing Test CVMFS with external cache plugins (Fri Feb 23 16:26:01 CET 2024 / test number 089)` is failing. 
i tried:
- moving the `!found` back to its old location
- removed the `return` in `d.HasXattrs()`
- do both
in all cases it fails on my local machine. (still need to chekc if with normal devel it works, might also something that is not correctly set up on my machine)

also note: ESTALE is not an official return error code for getxattr. we might need to change that.

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
@cernvm-bot help

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest nodestroy

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
Integration test problem solved by #3521

**Review by vvolkl — APPROVED** [review]

**Review by jblomer — APPROVED** [review]
LGTM.
As a follow-up minor optimization, the parsing of the attribute name could go in its own (static) function, which would be called before entering the remount fence. This can be a follow-up PR.

**Pull request merged**
