### PR TITLE
Fix gitignore

### PR DESCRIPTION
**Pull request by PerilousApricot**
Add more matches to keep the repository "clean" with a currently built
working area

### CODE REVIEW

**Comment by jblomer** [comment]
Thank you for the patch!  Now, I wonder if this is the best default for all the developers.  We normally use a different directory for building so that the source tree doesn't get polluted in the first place.  Would that work for you?

**Comment by PerilousApricot** [comment]
I don't think it hurts to have these in the .gitignore since they are all specific files and not wildcards (i.e. adding *.cmake would be overly broad).

**Comment by jblomer** [comment]
That's fine for merging if it solves a particular problem and doesn't introduce a new one.  @reneme do you have any objections?

@PerilousApricot Can you explain why building out of the source tree doesn't work for you?

**Comment by reneme** [comment]
No objections from my side. Sound reasonable to me to 'support' in-place build to give developers a choice.

**Pull request merged**
