### PR TITLE
externals: update to pacparser 1.4.3

### LINKED ISSUE #3594: libpacparser won't build with Python 3.12
Python 3.12 has done away with distutils

```
make clean && make for libpacparser (omitting test execution)...
make[1]: Entering directory '/home/git/cvmfs-2.11/externals_build/build_pacparser/src'
rm -f libpacparser.so libpacparser.so.1 pacparser.o pactester pymod/pacparser_o_buildstamp jsapi_buildstamp
rm -rf dist
cd pymod && python3 setup.py clean --all
Traceback (most recent call last):
  File "/home/git/cvmfs-2.11/externals_build/build_pacparser/src/pymod/setup.py", line 37, in <module>
    import distutils
ModuleNotFoundError: No module named 'distutils'
```

### PR DESCRIPTION
**Pull request by vvolkl**
This lets CVMFS build against python 3.12. No other changes expected, see https://github.com/manugarg/pacparser/releases/tag/v1.4.3

Fixes #3594

### CODE REVIEW

**Comment by vvolkl** [comment]
I added Fedora 40 as a platform to test this, but gcc 14 ran into https://stackoverflow.com/questions/8047362/is-gcc-mishandling-a-pointer-to-a-va-list-passed-to-a-function . Will still add a patch and report upstream

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
Still ironing out some issues related to the update of platforms.

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot  cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot  cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Review by jblomer — APPROVED** [review]

**Pull request merged**
