### PR TITLE
Telemetry: add support for statistic counters that need manual update

### PR DESCRIPTION
**Pull request by HereThereBeDragons**
Issue #3675

### CODE REVIEW

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
Test failure unrelated, LGTM.

Fixes #3675

**Pull request merged**
