### PR TITLE
Clean up proxy server selection logic

### PR DESCRIPTION
**Pull request by mcb30**
Clean up the logic around proxy server selection, in preparation for adding the ability to load-balance across multiple active proxy servers.

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Comment by jblomer** [comment]
@cernvm-bot tidy

**Comment by mcb30** [comment]
> cloudtests finished: FAILURE https://lcgapp-services.cern.ch/cvmfs-jenkins/job/CvmfsCloudTesting/1245/

Unrelated random failures, as far as I can tell.

**Review by jblomer — APPROVED** [review]

**Pull request merged**
