### PR TITLE
Fix gateway uploader finalization

### PR DESCRIPTION
**Pull request by jblomer**
@siscia That should fix the hang you saw when working on #2619 

(Note to ourselves: there is unfortunately quite a bit of disorder in the uploader / spooler / session context set of classes.  Tracked in CVM-1932)

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by siscia** [comment]
Thanks! I will rebase #2619 on top of this one.

**Comment by jblomer** [comment]
The standard gateway tests now go through, the "gateway - missing reflog" test still seems sick. Looking into it.

**Comment by siscia** [comment]
Yes, the test keep failing. But even before the commit that I pointed out.

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Pull request merged**
