### PR TITLE
Improve performance of cache cleanup

### LINKED ISSUE #3491: Client stalls during cache manager cleanup, slow cleanup.
I've noticed that when the posix cache manager is in DoCleanup(), it is nonresponsive to attached cvmfs2 clients, which will stall until the cleanup is finished. Sometimes DoCleanup() appears to spend a surprisingly long amount of time in cleanup, I suspect due to extreme fragmentation of the backing sqlite file. 

Representative stack trace -completion of DoUpdate() is taking 100s of seconds(!). `cachedb` file is ~13MB in size. It seems like the execution of the query ```SELECT sha1, size FROM cache_catalog WHERE acseq=(SELECT min(acseq) FROM cache_catalog WHERE pinned<>2);``` is being very slow.
Interestingly, execution of that query in the sqlite3 cli against  a copy of the db file is instantaneous.
```
Thread 2 (Thread 0x7ffff4de8700 (LWP 60788)):
#0  0x00007ffff6ddbac1 in poll () from /lib64/libc.so.6
#1  0x00007ffff63c0358 in Watchdog::MainWatchdogListener (data=0x62c270) at /root/cvmfs/cvmfs/monitor.cc:568
#2  0x00007ffff79b31cf in start_thread () from /lib64/libpthread.so.0
#3  0x00007ffff6cf0dd3 in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7ffff7fdc740 (LWP 60783)):
#0  0x00007ffff79bcaa4 in read () from /lib64/libpthread.so.0
#1  0x00007ffff64cd7f4 in unixRead () from /usr/lib64/libcvmfs_fuse3.so
#2  0x00007ffff64c9037 in sqlite3OsRead () from /usr/lib64/libcvmfs_fuse3.so
#3  0x00007ffff64edb32 in readDbPage () from /usr/lib64/libcvmfs_fuse3.so
#4  0x00007ffff64fc53a in getPageNormal () from /usr/lib64/libcvmfs_fuse3.so
#5  0x00007ffff64ca3e9 in sqlite3PagerGet () from /usr/lib64/libcvmfs_fuse3.so
#6  0x00007ffff64ed48a in getAndInitPage () from /usr/lib64/libcvmfs_fuse3.so
#7  0x00007ffff64ed586 in moveToChild () from /usr/lib64/libcvmfs_fuse3.so
#8  0x00007ffff64ed60d in moveToLeftmost () from /usr/lib64/libcvmfs_fuse3.so
#9  0x00007ffff6501d15 in sqlite3BtreeNext () from /usr/lib64/libcvmfs_fuse3.so
#10 0x00007ffff6501cb8 in btreeNext () from /usr/lib64/libcvmfs_fuse3.so
#11 0x00007ffff6501d06 in sqlite3BtreeNext () from /usr/lib64/libcvmfs_fuse3.so
#12 0x00007ffff6501d9d in sqlite3BtreeTableMoveto () from /usr/lib64/libcvmfs_fuse3.so
#13 0x00007ffff6501f56 in sqlite3VdbeFinishMoveto () from /usr/lib64/libcvmfs_fuse3.so
#14 0x00007ffff651b2b0 in sqlite3VdbeExec () from /usr/lib64/libcvmfs_fuse3.so
#15 0x00007ffff6522351 in sqlite3_step () from /usr/lib64/libcvmfs_fuse3.so
#16 0x00007ffff63e7c69 in PosixQuotaManager::DoCleanup (this=this@entry=0x7fffffffbb00, leave_size=10485760000) at /root/cvmfs/cvmfs/quota_posix.cc:440
#17 0x00007ffff63e82ad in PosixQuotaManager::ProcessCommandBunch (this=this@entry=0x7fffffffbb00, num=num@entry=32, commands=commands@entry=0x7fffffff79b0, descriptions=descriptions@entry=0x7fffffff7fb0 "file catalog at XXXXXXX (2def76968729b1d36fd055e9fd115284cdbe49d7)42bc7ec9d55f)a5fa))a))c)8)") at /root/cvmfs/cvmfs/quota_posix.cc:1634
#18 0x00007ffff63e98e0 in PosixQuotaManager::MainCommandServer (data=data@entry=0x7fffffffbb00) at /root/cvmfs/cvmfs/quota_posix.cc:1273
#19 0x00007ffff63ea30d in PosixQuotaManager::MainCacheManager (argc=argc@entry=11, argv=argv@entry=0x7fffffffc148) at /root/cvmfs/cvmfs/quota_posix.cc:1068
#20 0x00007ffff63fa9d3 in AltProcessFlavor (argc=11, argv=0x7fffffffc148) at /root/cvmfs/cvmfs/cvmfs.cc:2508
#21 0x00007ffff6a98506 in FuseMain (argc=11, argv=0x7fffffffc148) at /root/cvmfs/cvmfs/loader.cc:699
#22 0x0000000000404241 in main (argc=11, argv=0x7fffffffc148) at /root/cvmfs/cvmfs/fuse_main.cc:144
```

Approximate steps to reproduce:
* set up a repo with a few million catalogs
* setup a client with a posix cache , of small size
* run a loop of `find -type d` over the repo
* observe find stalls when cache manager is in DoCleanUp() , when`clean up cache until at most XXX KB is used` is syslogged
* After a few days, you should see  the cache manager process start to spend much more time in DoCleanUp()

### PR DESCRIPTION
**Pull request by jblomer**
Currently, during eviction, the cache database is processed entry-by-entry with (usually) two SQL queries per entry (select + remove). This PR changes the processing to batch selection (1000 entries per batch) and a single remove call per cache cleanup. The unit tests show a drastic improvement for 50000 entries from a few 100ms to <1ms.

Fixes #3491

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot unittest

**Review by vvolkl — APPROVED** [review]

**Pull request merged**
