### PR TITLE
Updating pacparser

### LINKED ISSUE #2872: New pacparser version 1.3.9 available
[pacparser 1.3.8](https://github.com/manugarg/pacparser/releases/tag/v1.3.8) has been released.  Update to that version when convenient.

### PR DESCRIPTION
**Pull request by radupopescu**
Addresses #2872

### CODE REVIEW

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
Build failure ☝️  seems to be due to Python.

**Comment by DrDaveD** [comment]
You might want to wait on this anyway, because the author of pacparser is processing a lot more PRs and I suspect another release will be coming soon.

**Comment by radupopescu** [comment]
@cernvm-bot unittest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
Closing this, as in #2963 updating pacparser to version 1.4.0 was needed for fix compilation on macOS.

**Pull request closed without merging**
