### PR TITLE
Add logging and counters to all EIOs

### PR DESCRIPTION
**Pull request by mharvey-jt**
Log and count all EIOs that get returned by fuse operations.

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Comment by jblomer** [comment]
@cernvm-bot tidy

**Comment by mharvey-jt** [comment]
@cernvm-bot cpplint

**Comment by mharvey-jt** [comment]
@HereThereBeDragons updated, could you lint etc please?

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cpplint

**Comment by HereThereBeDragons** [comment]
@cernvm-bot tidy

**Comment by jblomer** [comment]
@mharvey-jt Do you have any information about how frequently errors are logged to syslog? What I wonder is if we should channel these messages, at least optionally, to a different file. These EIO errors may not be a fault of the client but really due to poor structure/publishing on the repository side (e.g., removal of a directory tree in use).

**Comment by mharvey-jt** [comment]
Infrequently, in our experience. It may well be possible to engineer a situation in which the syslog get spammed, but I'd expect journald's rate-limiting to suppress duplicate messages

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Review by jblomer — APPROVED** [review]

**Pull request merged**
