### PR TITLE
Fix test 705-servercheck-hashmap

### PR DESCRIPTION
**Pull request by vvolkl**
The test checks for the log, expecting a higher verbosity that was not set.

### CODE REVIEW

**Review by jblomer — CHANGES_REQUESTED** [review]
Should also become a quick test

**Comment by vvolkl** [comment]
It's not that quick though; takes around 10 min. Can be made faster, so I'd propose to do this in a future PR.

EDIT, scratch that, it's 10 sec, so yes, will add it to quick suite too.

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Review by jblomer — APPROVED** [review]

**Comment by vvolkl** [comment]
This check here is flaky: https://github.com/cvmfs/cvmfs/pull/3346/files#diff-b4ab84b9d199714f8d17be0c0117bacbdf7dfcb5b5a13612dfda926a943332c1R41

It's not always testdata/b that is checked second. Will update the regexp/

**Comment by vvolkl** [comment]
@cernvm-bot  cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Pull request merged**
