### PR TITLE
Fix lease statistics extraction during commit

### PR DESCRIPTION
**Pull request by radupopescu**

### CODE REVIEW

**Comment by radupopescu** [comment]
@cernvm-bot help

**Comment by radupopescu** [comment]
@cernvm-bot unittest gw

**Comment by radupopescu** [comment]
@cernvm-bot unittest

**Review by jblomer — APPROVED** [review]
Great!  Let's run the integration tests (`cernvm-bot cloudtest`) before merging.

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Pull request merged**
