### PR TITLE
Add hardlinks support to tarball ingestion

### PR DESCRIPTION
**Pull request by siscia**
In this PR we add support for hardlinks.

It was required to add an aadditional function `Link` to the catalog manager

### CODE REVIEW

**Comment by siscia** [comment]
I believe is better to wait the merge of all the other PR before to fix the several conflicts in this one.

**Comment by jblomer** [comment]
Please give a more meaningful title to the PR.

**Comment by siscia** [comment]
Sorry, I was too deep into this specific branch of development.

**Comment by siscia** [comment]
Supersed by #2147

**Pull request closed without merging**
