### PR TITLE
Fix 'mount -o remount' syntax

### LINKED ISSUE #3472: Adjust to syntax of newer mount versions
Newer versions of the mount command require the syntax `mount -o remount,<flags> <device> <path>`, whereas older versions accept the syntax without the device argument, which cvmfs currently uses.

### PR DESCRIPTION
**Pull request by jblomer**
Newer versions of the mount command require the syntax mount -o remount,<flags> <device> <path>, whereas older versions accept the syntax without the device argument, which cvmfs currently uses.

Fixes #3472

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot unittest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Review by vvolkl — APPROVED** [review]

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Pull request merged**
