### PR TITLE
Cleanup unused files in the top level directory

### PR DESCRIPTION
**Pull request by vvolkl**
* cloc can now be installed from apt/dnf package repositories, no need to keep the script in the repo
* travis hasn't run in a while, unlikely to be used again
* badge in Readme.md updated to point to gh acations
* NEWS has never been filled, would use website instead
* changelog scripts can be done from the command line fairly easily
* test_mount script seems useful, but can be moved to tests
* the cvmfs_config.h header is for autotools compatibility, no longer needed
* the only thing still used from cvmfs_config.h are the version definitions, moved those to CMakeLists.txt
* renamed the definition VERSION -> CVMFS_VERSION for better greppability
* some tidy fixes for files touched

### CODE REVIEW

**Review by jblomer — APPROVED** [review]

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
Should add a `.git-blame-ignore-revs` file after this.

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Pull request merged**
