### PR TITLE
Update maxmind reader to v1.5.4

### PR DESCRIPTION
**Pull request by jblomer**

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
It looks good to me, the test failures are unrelated. @DrDaveD If you have no objections, I'd merge this by tomorrow.

**Comment by DrDaveD** [comment]
I don't have any objections.

**Pull request merged**
