### PR TITLE
ducc convert: sleep briefly between wishes to avoid load spikes on registries

### PR DESCRIPTION
**Pull request by vvolkl**

### CODE REVIEW

**Comment by jblomer** [comment]
How much longer will it take to process the wishlist with this patch? Just to make sure we stay comfortably in the 10 minute window.

**Comment by vvolkl** [comment]
@jblomer it should add about 7.5 minutes of sleep time, is that too much?

**Comment by jblomer** [comment]
It will probably still work but I think it should be seen a stopgap solution. The wish list will most likely grow.

**Comment by vvolkl** [comment]
Superseded by #3248

**Pull request closed without merging**
