### PR TITLE
Feature azureblob: adding test using azurite [v2]

### PR DESCRIPTION
**Pull request by jblomer**
Replaces #2776 

Missing bit: 
- [x] azurite installation on Ubuntu

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by hmeiland** [comment]
thanks for all the updates/checks!

**Pull request merged**
