### PR TITLE
Explicit python2 in integration tests

### PR DESCRIPTION
**Pull request by janpriessnitz**
Fix shebangs in all related files.
Make a switch between python/python2 for tests
running on macOS, too.

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by janpriessnitz** [comment]
@jblomer I would like to run full cloudtests overnight to see what else could be failing. Please do not merge immediately.

**Comment by jblomer** [comment]
@janpriessnitz ok

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest nodestroy

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest

**Comment by janpriessnitz** [comment]
@jblomer ready to merge. The failures in last cloudtest are unrelated to this PR.

**Pull request merged**
