### PR TITLE
Install systemd/autofs patch configuration through RPM where necessary -- 2.3

### PR DESCRIPTION
**Pull request by jblomer**

### CODE REVIEW

**Comment by DrDaveD** [comment]
Shouldn't you also undo the creation of the corresponding file under /etc/systemd?

**Comment by jblomer** [comment]
No, everything else stayed as is.  If `cvmfs_config setup` discovers that autofs' `KillMode` is not `process`, it will still drop a patch file into /etc/systemd.  So there can be situations in which the cleanup is necessary.

**Comment by jblomer** [comment]
Sorry, that's about removal of the file in /etc/systemd.  About creation: if the `KillMode` already is `process`, nothing needs to be dropped and the file is not created.  So we can leave that in.

**Comment by DrDaveD** [comment]
Alright, cool

**Comment by jblomer** [comment]
Thanks for testing!

**Pull request merged**
