### PR TITLE
Fix test 602: static library renamed

### PR DESCRIPTION
**Pull request by vvolkl**
See https://github.com/cvmfs/cvmfs/pull/3113

### CODE REVIEW

**Review by jblomer — CHANGES_REQUESTED** [review]
While we are at it, let's add this test to the quick test suite.

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Review by jblomer — APPROVED** [review]

**Comment by vvolkl** [comment]
There's a segfault only on el7, will have to look into what is happening there.

**Comment by vvolkl** [comment]
The segfault is coming from libcrypto on el7:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff709cf05 in OPENSSL_ia32_cpuid () from /lib64/libcrypto.so.10
```
Do we want to support libcvmfs on this platform or  do we just skip the test there?

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
That's strange, it seems to only happen on the S3 platform.

**Comment by vvolkl** [comment]
> That's strange, it seems to only happen on the S3 platform.

No, I already excluded the regular el7, (thinking partial test coverage now  is preferable and wanting to move this to an issue), I just forgot about el7_s3.

**Comment by jblomer** [comment]
See #3351: I think there was an underlying problem with the symbol visibility in libcvmfs_crypto

**Pull request merged**
