### PR TITLE
Allow Parrot execution of integration tests

### PR DESCRIPTION
**Pull request by Moliholy**
This enables run.sh to execute tests through Parrot. It doesn't mean all tests can now be executed with Parrot, but that they "could" if they don't use fuse (or sudo, in any case).

An idea to identify the tests that can run with parrot would be to manually include a variable, say CVMFS_PARROT_ALLOWED=true, in those tests that can actually run it, and set it to false by default.

Note: when running with Parrot the variable PARROT_ENABLED is set to TRUE

### CODE REVIEW

**Comment by jblomer** [comment]
Could it be that commits are missing from this PR?

**Comment by Moliholy** [comment]
No, in principle it's fine. It simply allows run.sh to execute tests with Parrot. Before it was impossible due to the sudo's. Now what we should do is to agree in how we want to organise the way integration tests run under Parrot, and I simply suggested a way, but that's something we should talk about.
Independently on the solution we finally choose, all the changes in this PR are necessary to avoid crashes at the beginning when running with Parrot

**Comment by jblomer** [comment]
Ok, so there are more PRs to come, right?

**Comment by Moliholy** [comment]
Yes, once we talk and discuss the preferred way to do it

**Pull request merged**
