### PR TITLE
Add a hidden `cvmfs_server eliminate-bulk-hashes` command

### PR DESCRIPTION
**Pull request by jblomer**
The command removes bulk hashes from files that also exist in chunked form.

### CODE REVIEW

**Comment by DrDaveD** [comment]
@jblomer Let me know when this is ready for testing and I'll try it out on the UNL test stratum 1.

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@DrDaveD See http://ecsft.cern.ch/dist/cvmfs/nightlies/cvmfs-git-2169/

**Comment by jblomer** [comment]
@DrDaveD Sorry, it's this one: http://ecsft.cern.ch/dist/cvmfs/nightlies/cvmfs-git-2170/

**Comment by DrDaveD** [comment]
2169 had the command.  

I hadn't thought it through enough to realize it would only work on stratum 0s, but of course that's the case.  The smallest repository I found that was affected was geant4.cern.ch, so on my test stratum 1 I converted that repository into a stratum 0 with rmfs -p and import -t -r.  It required a masterkey which I didn't have handy so I created a temporary repository, copied the .masterkey and .pub, and deleted the temporary repository.  I had quite a hassle with import complaining about no .cvmfsreflog so I should delete reflog.chksum, but there was no such file.  I figured out it was reading the hash from .cvmfspublished, and was able to get it to work after downloading .cvmfsreflog from the FNAL stratum 1.  I ran eliminate-bulk-hashes, enabled gc and ran it, but it didn't delete the bulk files.  Now I'm taking a fresh snapshot which should hopefully do it.

**Comment by DrDaveD** [comment]
Nope, the fresh snapshot too has large files that have no letter extension on them, for example these in `/srv/cvmfs/geant4-new.cern.ch/data/00`:
```
$ ls -s|awk '{if ($1 > 17000) print}'
total 733822
 19217 88094ea0369b68714f5318ec0e901768202ebc
119121 9fbd60aa247b11bbc4aae4d4903438dd85b97c
115409 cc3733016902bf36991b461828e69a270940b1
```

**Comment by DrDaveD** [comment]
In case it helps, I decompressed that second file and found its location in the repository:
```
-rwxr-xr-x 1 309 309 366898181 Dec  7  2017 /cvmfs/geant4.cern.ch/geant4/10.4/x86_64-slc6-gcc63-opt/lib64/libG4processes.so
```

**Comment by jblomer** [comment]
The command removes the reference of bulk hashes from the trunk catalog revision.  You might have it still referenced in previous tags (e.g. `trunk-previous`). The garbage collection can only kick in once all the historic tags are phased out (by more recent publishes) or removed.

**Comment by DrDaveD** [comment]
Yes, very good.  I deleted all the old tags, and then gc cleaned them up.  It saved over a third of the space in geant4.cern.ch, around 55G out of 150G.  I'll try it on cms.cern.ch next.

**Comment by DrDaveD** [comment]
I hit a problem with cms.cern.ch.  It died with a "local I/O failure":
```
061db63f078f15ec05c7d13fc399243f29a95bb3 /slc6_amd64_gcc700/external/mctes25.0a-gnimlf2
failed to load catalog b7be19c908d97da5131e07f823f84037d12d98d2C (2 - local I/O failure)
Failed to load catalog tree
Fail (executed command: cvmfs_swissknife migrate -v 'bulkhash' -r http://localhost/cvmfs/cms.cern.ch -n cms.cern.ch -u local,/srv/cvmfs/cms.cern.ch/data/txn,/srv/cvmfs/cms.cern.ch -k /etc/cvmfs/keys/cms.cern.ch.pub -s -t /var/spool/cvmfs/cms.cern.ch/tmp -o /var/spool/cvmfs/cms.cern.ch/tmp/manifest)
```
The apache log showed the file downloaded OK.  I ran it twice and it stopped at the same point.  I thought it might be a file descriptor problem, and indeed after I increased ulimit -n from 16384 to 132000 it has gotten past that point and is still running.

**Comment by DrDaveD** [comment]
Here are the results of eliminating bulk hashes on cms.cern.ch.  First, the summary output of the command:
```
Actual Entries:                166022984
Allocated Inodes:              170123291
  Unused Inodes:               4100307
  Percentage of wasted Inodes: 2.4%

Generated Hardlink Groups:     0
Average Linkcount per Group:   0.0

Catalog Loading Time:          1636.63s
Average Migration Time:        0.10s
Overall Migration Time:        207.28s
Aggregated Migration Time:     3133.66s
```
I then deleted all tags except for trunk and trunk-previous and did a couple of more transaction/publishes.  I then ran gc, and it did not reduce the size at all.  I then took a fresh snapshot, and the du -ks size went down from 7522171287 to 4790299925, that is, 2.5T! 

However, not all larger files were eliminated.   In the data/00 directory, there are 3 files bigger than 17000K:
```
21393 18eb425d96ccef7cbf94e5c489ce8e4590d294
23833 418d8c130aaf3dfabd4e4485777a829338bedf
81977 eb3894d66c4984ad56438f45a686edc5b49a91
```
I did zpipe -d on the third one, searched by size in the repository, and found it in several places:
```
/cvmfs/cms.cern.ch/slc5_amd64_gcc472/cms/data-FastSimulation-PileUpProducer/V04-05-18-cms/FastSimulation/PileUpProducer/data/MinBias13TeV_002.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc472/cms/data-FastSimulation-PileUpProducer/V04-05-18-cms2/FastSimulation/PileUpProducer/data/MinBias13TeV_002.root
/cvmfs/cms.cern.ch/slc5_amd64_gcc481/cms/data-FastSimulation-PileUpProducer/V04-05-18-cms/FastSimulation/PileUpProducer/data/MinBias13TeV_002.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/data-FastSimulation-PileUpProducer/V04-05-18-cms/FastSimulation/PileUpProducer/data/MinBias13TeV_002.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc490/cms/data-FastSimulation-PileUpProducer/V04-05-18/FastSimulation/PileUpProducer/data/MinBias13TeV_002.root
/cvmfs/cms.cern.ch/fc19_aarch64_gcc490/cms/data-FastSimulation-PileUpProducer/V04-05-18/FastSimulation/PileUpProducer/data/MinBias13TeV_002.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/data-FastSimulation-PileUpProducer/V04-05-18/FastSimulation/PileUpProducer/data/MinBias13TeV_002.root
/cvmfs/cms.cern.ch/osx108_amd64_gcc481/cms/data-FastSimulation-PileUpProducer/V04-05-18-cms/FastSimulation/PileUpProducer/data/MinBias13TeV_002.root
```

**Comment by jblomer** [comment]
Interesting!  For the remaining large files, CMS needs to touch them to trigger re-publication in chunks.

Not sure why the cvmfs gc did not kick in.  It might have saved the last few revisions behind your back.  Can you try with `cvmfs_server gc -r0` which should avoid the silently kept revisions.

**Comment by DrDaveD** [comment]
Using gc -r0 worked.

I found there are 487 remaining files greater than 17000K compressed, adding up to only 15G.  It's not worth doing anything about them to save space, but if the files are still accessed I'd be concerned about the impact they might have on squids. All but 8 are less than 100M, and only two are more than 160M (a 311M and a 556M) so maybe I'll only ask them to republish those.   They both appear multiple times, the bigger one:
```
/cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc5_amd64_gcc470/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc5_amd64_gcc472/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/share/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc472/cms/data-SimG4CMS-Forward/V02-03-18-cms/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc480/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc5_amd64_gcc481/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc490/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/fc19_aarch64_gcc490/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc5_amd64_gcc480/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc462/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/osx108_amd64_gcc481/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
/cvmfs/cms.cern.ch/slc7_amd64_gcc493/cms/data-SimG4CMS-Forward/V02-03-18/SimG4CMS/Forward/data/CastorShowerLibrary_CMSSW500_Standard.root
```
and the other one:
```
/cvmfs/cms.cern.ch/slc5_amd64_gcc481/cms/data-SimG4CMS-Calo/V02-03-07-cms/SimG4CMS/Calo/data/HFShowerLibrary_npmt_eta4_16en.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/data-SimG4CMS-Calo/V02-03-07-cms/SimG4CMS/Calo/data/HFShowerLibrary_npmt_eta4_16en.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc490/cms/data-SimG4CMS-Calo/V02-03-07-cms/SimG4CMS/Calo/data/HFShowerLibrary_npmt_eta4_16en.root
/cvmfs/cms.cern.ch/fc19_aarch64_gcc490/cms/data-SimG4CMS-Calo/V02-03-07/SimG4CMS/Calo/data/HFShowerLibrary_npmt_eta4_16en.root
/cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/data-SimG4CMS-Calo/V02-03-07/SimG4CMS/Calo/data/HFShowerLibrary_npmt_eta4_16en.root
```

**Pull request merged**
