### PR TITLE
replace asserts() with return error

### PR DESCRIPTION
**Pull request by mharvey-jt**
https://github.com/cvmfs/cvmfs/issues/2896

### CODE REVIEW

**Comment by mharvey-jt** [comment]
@HereThereBeDragons rebased, could you lint etc please?

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cpplint

**Comment by HereThereBeDragons** [comment]
@cernvm-bot clang-tidy

**Comment by HereThereBeDragons** [comment]
@cernvm-bot  tidy

**Comment by HereThereBeDragons** [comment]
Superseded by #3169

**Pull request closed without merging**
