### PR TITLE
Fix path for pidof in cvmfs_config setup for Gentoo

### PR DESCRIPTION
**Pull request by APN-Pucky**
Closes: https://bugs.gentoo.org/917748

### CODE REVIEW

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Review by vvolkl — APPROVED** [review]
Thanks!

**Comment by APN-Pucky** [comment]
> cloudtests finished: FAILURE https://lcgapp-services.cern.ch/cvmfs-jenkins/job/CvmfsCloudTesting/1996/

Was that me? I doubt so unless the fails are by systems which don't have `pidof` in either of the 3 locations.

**Comment by vvolkl** [comment]
@APN-Pucky No, tests look good, the failures are unrelated.  Thanks again!

**Pull request merged**
