### PR TITLE
Fixing deb packaging on Ubuntu 22.04

### PR DESCRIPTION
**Pull request by radupopescu**

### CODE REVIEW

**Comment by jblomer** [comment]
Should we make the fixups in the debian packaging explicit, with a `debian/control.in` file that has the variable bits clearly marked, e.g. `CVMFS_PYTHON_DEV` etc?

**Comment by radupopescu** [comment]
Makes sense.

**Comment by radupopescu** [comment]
An update here. I'm not able to reproduce and understand the CI build failures we see for Ubuntu 22.04. I'd like to have a working build for Ubuntu 22.04 before releasing CVMFS 2.9.3

**Comment by radupopescu** [comment]
@cernvm-bot tidy

**Pull request merged**
