### PR TITLE
minimise cache overflow by closing fd at end of fuse_read()

### PR DESCRIPTION
**Pull request by mharvey-jt**
See  #2948

### CODE REVIEW

**Comment by mharvey-jt** [comment]
@jblomer this one's another high-priority bug I overlooked. Should I hide it behind a configuration option?

**Comment by mharvey-jt** [comment]
Added configuration option `CVMFS_CLOSE_CHUNK_FD_AFTER_READ`

**Comment by mharvey-jt** [comment]
@cernvm-bot clang-tidy

**Comment by mharvey-jt** [comment]
@cernvm-bot tidy

**Comment by jblomer** [comment]
Closing, replaced by mitigation in #3263

**Pull request closed without merging**
