### PR TITLE
Trim whitespace from list values in config file

### PR DESCRIPTION
**Pull request by amalthundiyil**
What:
Trims whitespace from all list elements in a config file if the delimiter is specified.

Why:
https://github.com/cvmfs/cvmfs/issues/3572

### CODE REVIEW

**Comment by HereThereBeDragons** [comment]
@cernvm-bot unittest

**Comment by HereThereBeDragons** [comment]
@cernvm-bot tidy

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cpplint

**Comment by amalthundiyil** [comment]
@cernvm-bot tidy

**Comment by amalthundiyil** [comment]
@cernvm-bot unittest

**Comment by amalthundiyil** [comment]
@cernvm-bot cpplint

**Comment by amalthundiyil** [comment]
@cernvm-bot unittest

**Pull request closed without merging**
