### PR TITLE
Update geo api for python3

### PR DESCRIPTION
**Pull request by DrDaveD**
See [CVM-2052](https://sft.its.cern.ch/jira/browse/CVM-2052)

### CODE REVIEW

**Comment by radupopescu** [comment]
Thanks for the patch!

**Comment by radupopescu** [comment]
@cernvm-bot tidy

**Comment by radupopescu** [comment]
@cernvm-bot cpplint

**Comment by radupopescu** [comment]
@cernvm-bot unittest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
This seems to be breaking the RPM builds for EL8:
```
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
*** WARNING: ./usr/libexec/cvmfs/shrinkwrap/spec_builder.py is executable but has no shebang, removing executable bit
*** WARNING: ./usr/libexec/cvmfs/ducc/registry-webhook.py is executable but has no shebang, removing executable bit
*** ERROR: ambiguous python shebang in /var/www/wsgi-scripts/cvmfs-server/cvmfs-api.wsgi: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
error: Bad exit status from /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/TMP/rpm-tmp.WGart7 (%install)
    Bad exit status from /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc8/build/TMP/rpm-tmp.WGart7 (%install)
```

**Comment by DrDaveD** [comment]
Ok I'll change it to python3 just to make rpmbuild happy, although it's really not relevant since python3-mod_wsgi starts python itself and ignores the shebang.

**Comment by radupopescu** [comment]
Thanks for updating it!

**Comment by jblomer** [comment]
@DrDaveD @radupopescu I think we also need to update the package sources to depend on python 3.

**Comment by DrDaveD** [comment]
That might separately be a good thing but I don't believe it is necessary because as I said the .wsgi file in cvmfs does not end up executing python, it is the python3-mod_wsgi module that does it.  I'm pretty sure that is the default mod_wsgi in el8, and at run time cvmfs-server requires mod_wsgi.  I have evidence that somebody who tried to run the geo api on an el8 machine had errors because python3 had tried to execute it.

**Comment by jblomer** [comment]
Ok, that makes sense. No need then to edit the package sources. Thanks for the clarification!

**Comment by jblomer** [comment]
(Note: The PR has been backported to the cvmfs-2.9 branch)

**Pull request merged**
