### PR TITLE
Ingest Tarball now with modifiyable ownership

### PR DESCRIPTION
**Pull request by HereThereBeDragons**
`cvmfs_ingest` has now 3 new command parameters to control ownership of files ingested:
```
# either
-u / --user uid
-g / --group gid
# or
-k / -keep-ownership
```

`group` can only be applied if also `user` is given.
if `keep-ownership` is set, neither `user` or `group` can be set

default behavior is to set the new owner to be the cvmfs repo owner

this ownership change only affects files, not directories. directories are always owned by the cvmfs repo owner.
(not sure if we want this.. but there the mechanics for it seems to be not in easy to reach places)

for the `swissknife ingest` command the new params are (no check is done if they are valid):
```
-U uid # if set to -1 == keep-ownership
-G gid # if set to -1 == keep-ownership
```

### CODE REVIEW

**Comment by HereThereBeDragons** [comment]
Issue #3073

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
ps. there might be some issues with the bash?
```
Checking storage integrity of just.test.repo ... (may take a while)
Verifying integrity of just.test.repo...
Inspecting log of references
Inspecting tag database
[inspecting catalog] 715afbe1e841fb126189042724dd510c34f23147 at /
no problems found
/usr/bin/cvmfs_server: 2178: return: Illegal number: 
total 15K
```
and
```
*** 2) ingesting the tarball again in the directory tar_dir: everything owned by root
/usr/bin/cvmfs_server: 9236: eval: [[: not found
Using auto tag 'generic-2023-08-11T13:54:16Z'
Processing changes...
Waiting for upload of files before committing...
Committing file catalogs...
Wait for all uploads to finish
```

**Comment by HereThereBeDragons** [comment]
@cernvm-bot unittest

**Comment by HereThereBeDragons** [comment]
@cernvm-bot help

**Comment by HereThereBeDragons** [comment]
@cernvm-bot tidy

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
@cernvm-bot tidy

**Review by vvolkl — APPROVED** [review]
Very nice!

**Pull request merged**
