### PR TITLE
exclude tests expected to fail streamingcache test suite

### PR DESCRIPTION
**Pull request by vvolkl**
@jblomer These are the tests failing the streaming cache test suite in https://github.com/cvmfs/cvmfs/pull/3630  - to me it looks like they are all expected failures.

### CODE REVIEW

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by DrDaveD** [comment]
I think it was an error that a test/src/602-libcvmfs/test binary file got added in this PR.

**Comment by DrDaveD** [comment]
> I think it was an error that a test/src/602-libcvmfs/test binary file got added in this PR.

I will remove it as part of #3730

**Pull request merged**
