### PR TITLE
Add `cvmfs_server enter` command

### PR DESCRIPTION
**Pull request by jblomer**
The `cvmfs_publish enter` command opens a writable subshell given read-only access to a repository.  It does so by

- Creating a user, mount, and pid namespace
- Creating an underlay using the current root file system tree
- Mounting /cvmfs/$repo with fuse-overlayfs

The state of the writable shell is kept in $HOME/.cvmfs

Corresponding ticket: https://sft.its.cern.ch/jira/browse/CVM-1924

### CODE REVIEW

**Comment by bedroge** [comment]
As I am quite curious how this works, I just compiled and installed this branch on a CentOS 8 VM. This allowed me to access our repositories, and to use use the `cvmfs_publish enter` command. I do get write permission in the corresponding repository, but for some reason it's completely empty:

```
[bob@10 ~]$ ls /cvmfs/pilot.eessi-hpc.org/
2020.08  2020.09  new_repository  test
[bob@10 ~]$ 
[bob@10 ~]$ cvmfs_publish enter pilot.eessi-hpc.org
Entering ephemeral writable shell for /cvmfs/pilot.eessi-hpc.org... 
underlay: entry  --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs
underlay: mkdir /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/cvmfs
underlay: entry /cvmfs --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/cvmfs
underlay: mkdir /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/cvmfs/pilot.eessi-hpc.org
underlay: /cvmfs/cvmfs-config.eessi-hpc.org --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/cvmfs/cvmfs-config.eessi-hpc.org
underlay: mkdir /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/proc
underlay: /boot --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/boot
underlay: /dev --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/dev
underlay: /disk2 --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/disk2
underlay: /etc --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/etc
underlay: /home --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/home
underlay: /media --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/media
underlay: /misc --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/misc
underlay: /mnt --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/mnt
underlay: /net --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/net
underlay: /opt --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/opt
underlay: /root --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/root
underlay: /run --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/run
underlay: /srv --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/srv
underlay: /sys --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/sys
underlay: /tmp --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/tmp
underlay: /usr --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/usr
underlay: /var --> /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs/var
Mounting CernVM-FS read-only layer... CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/lower_layer
done
Mounting union file system... done
Switching to /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/rootfs... done
[bob@10 ~]$ 
[bob@10 ~]$ ls /cvmfs/pilot.eessi-hpc.org/
[bob@10 ~]$ 
```

Am I doing something wrong?

**Comment by jblomer** [comment]
Hm, do you see the lower layer in the enter shell correctly populated, i.e. `ls /home/bob/.cvmfs/pilot.eessi-hpc.org/session.PjxxbG/lower_layer` not empty (the session directory changes with every enter invocation)

**Comment by bedroge** [comment]
That directory is empty as well. I also tried it with our cvmfs-config repo (since I figured that maybe the other one didn't work due to the dependency on the config repo), but it has the same issue:

```
CernVM-FS: mounted cvmfs on /home/bob/.cvmfs/cvmfs-config.eessi-hpc.org/session.rwnTKg/lower_layer
done
Mounting union file system... done
Switching to /home/bob/.cvmfs/cvmfs-config.eessi-hpc.org/session.rwnTKg/rootfs... done
[bob@10 ~]$ 
[bob@10 ~]$ ls /cvmfs
cvmfs-config.eessi-hpc.org
[bob@10 ~]$ ls /cvmfs/cvmfs-config.eessi-hpc.org/
[bob@10 ~]$ 
[bob@10 ~]$ ls /home/bob/.cvmfs/cvmfs-config.eessi-hpc.org/session.rwnTKg/lower_layer
[bob@10 ~]$ 
```

**Comment by jblomer** [comment]
Hm, there should be a `usyslog` file in the session directory.  Does it contain any messages that point to the problem?  Also, `cat /proc/mounts` inside the enter shell might provide some useful information.

**Comment by bedroge** [comment]
Figured it out while I was looking at `/proc/mounts` and didn't see an overlayfs: I didn't have `fuse-overlayfs` installed... oops :-)

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest cc7

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Pull request merged**
