### PR TITLE
Use http client auth only if membership is set

### PR DESCRIPTION
**Pull request by jblomer**
Suggested replacement for #3307

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
if this is the solution then we should remove this code section, as it will never be called. credential_attachement is always set in the mountpoint.

https://github.com/cvmfs/cvmfs/blob/8ed16ca371884fac90d2be44e5b76d13ec2cb7b3/cvmfs/network/download.cc#L935-L937

or replace the `if` with  `if (!credential_attachement.membership())` (just need to add it to the class, not sure how much effort that would be)

**Comment by jblomer** [comment]
This is only true if the download manager is created by the `Mountpoint` class. Otherwise (e.g., server), the attachment may or may not be set.

**Comment by HereThereBeDragons** [comment]
ok so should we extend the if? `if (credentials_attachment_ == NULL || (!credential_attachement.membership())`?

**Comment by jblomer** [comment]
> ok so should we extend the if? `if (credentials_attachment_ == NULL || (!credential_attachement.membership())`?

It may actually be a bit nicer to read that way, but it's also a slightly larger change because the membership information is only present in the derived class `AuthzAttachment`, and the download manager at this point has the base class `CredentialsAttachment` in its hand.  I'd suggest to leave it as is and perhaps come back to the credentials management at a later point.

**Comment by HereThereBeDragons** [comment]
ok should we then add some comment there?

> > ok so should we extend the if? `if (credentials_attachment_ == NULL || (!credential_attachement.membership())`?
> 
> It may actually be a bit nicer to read that way, but it's also a slightly larger change because the membership information is only present in the derived class `AuthzAttachment`, and the download manager at this point has the base class `CredentialsAttachment` in its hand. I'd suggest to leave it as is and perhaps come back to the credentials management at a later point.

**Comment by jblomer** [comment]
> ok should we then add some comment there?

I think that would be a bit of an arbitrary spot for what should be a more general review of the handling of client credentials. Issue #3342 created.

**Review by HereThereBeDragons — APPROVED** [review]

**Review by vvolkl — APPROVED** [review]

**Pull request merged**
