### PR TITLE
Add minimal cvmfs_util library

### PR DESCRIPTION
**Pull request by jblomer**
1st part of properly fixing #2990. Introduces a `cvmfs_util` library.  It currently contains only `string.cc`.  Once the mechanics works, in a next step, the util folder should be made self-contained and as a whole added to the `cvmfs_util` library.

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Pull request merged**
