### PR TITLE
HTTP Tracing

### PR DESCRIPTION
**Pull request by mharvey-jt**
When enabled, this feature adds additional headers to to all HTTP requests, allowing tracing of requests from FUSE request through HTTP caching layers. New configuration options:
```
CVMFS_HTTP_TRACING=on  (default off)
CVMFS_HTTP_TRACING_HEADERS="X-CVMFS-key1:  val1|X-CVMFS-key2: val2|...."     #'|'-delimited list of headers to include in trace
```
The headers added are:
```
X-CVMFS-PID: pid of process originating the fuse request
X-CVMFS-GID: gid "
X-CVMFS-UID: uid "
```
as well as any defined in the `CVMFS_HTTP_TRACING_HEADERS` configuration option

Testing this has the same challenge as https://github.com/cvmfs/cvmfs/pull/3102 - we'd need to log the headers. Could possibly do this by adding a feature to log all http requests at the Curl level with https://curl.se/libcurl/c/CURLOPT_VERBOSE.html

### CODE REVIEW

**Comment by jblomer** [comment]
I guess this is related to #3094

**Comment by mharvey-jt** [comment]
@jblomer  #3146 proposes a method to test this and #3102

**Comment by mharvey-jt** [comment]
@cernvm-bot unittest

**Comment by HereThereBeDragons** [comment]
Superseeded by #3308

**Pull request closed without merging**
