### PR TITLE
Fix x86_64 build on macOS

### PR DESCRIPTION
**Pull request by radupopescu**
* Fix includes in prng.h
* Updating pacparser to version 1.4.0

### CODE REVIEW

**Review by jblomer — APPROVED** [review]

**Comment by jblomer** [comment]
Fixes #2872

**Review by jblomer — DISMISSED** [review]
That may be a problem: unless sparsehash kept the in-memory layout the same, an update here will break the hotpatch because the information about currently open directories is kept in a sparsehash data structure.

**Comment by radupopescu** [comment]
> That may be a problem: unless sparsehash kept the in-memory layout the same, an update here will break the hotpatch because the information about currently open directories is kept in a sparsehash data structure.

I reverted to the original version of Sparsehash.

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot unittest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Pull request merged**
