### PR TITLE
Trivial cloudtesting fixes

### PR DESCRIPTION
**Pull request by janpriessnitz**

### CODE REVIEW

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest cc7

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest cc7

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest cc7

**Comment by jblomer** [comment]
@cernvm-bot help

**Comment by jblomer** [comment]
@cernvm-bot cloudtest nodestroy cc7

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest nodestroy cc7

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Pull request merged**
