### PR TITLE
add ducc and cmake to compile it

### PR DESCRIPTION
**Pull request by siscia**
Add ducc into the main repository

### CODE REVIEW

**Comment by jblomer** [comment]
The version is indeed tricky.  Let's check at least for a `go` compiler though.

**Comment by siscia** [comment]
@jblomer this version should be better indeed.

**Comment by radupopescu** [comment]
While I am working on fixing the Mac build, I needed to take the two nodes offline for testing.
I'll write back here once this is solved and Jenkins jobs can resume.

**Comment by radupopescu** [comment]
I brought back the old Mac node (running 10.13) so you can go ahead with the merges, if needed. The new node running 10.14 still needs work.

**Comment by siscia** [comment]
@jblomer would you mind have a look at the latest commit https://github.com/cvmfs/cvmfs/pull/2302/commits/68b1cb541ec25fb3fda2fbe1a122c10123063b4b and being sure that it is how we want to build ducc

**Pull request merged**
