### PR TITLE
MagicXattrRAIIWrapper add "The rule of three"

### PR DESCRIPTION
**Pull request by FanFansfan**
otherwise will unlock pthread_mutex twice and crash

### CODE REVIEW

**Comment by jblomer** [comment]
Many thanks for your contribution!  You are right, we should at least have a custom copy constructor and perhaps remove the copy assignment (so that we don't need to implement both). Just wondering because the code is like this for quite some time, did you actually experience a crash?

**Comment by FanFansfan** [comment]
> Many thanks for your contribution! You are right, we should at least have a custom copy constructor and perhaps remove the assignment constructor (so that we don't need to implement both). Just wondering because the code is like this for quite some time, did you actually experience a crash?

Yes. With gdb breakpoint set I observe the following execution sequence.
ed9306257cfd1e85ddaceb6b4269591
And crash backtrace log.
3b71f82f1375be4060591130479fcca

I suggest that we should also make copy assignment operator custom/private, or compiler will still invoke the implicitly-declared copy assignment operator. See https://wandbox.org/permlink/fhhYAiVg5Alo8vYT

**Review by jblomer — CHANGES_REQUESTED** [review]
In principle I agree.  What the code effectively does is implement the copy constructor as a move constructor. Given that the code base is C++98, we cannot use C++ move semantics.

So what I would propose is this:
  - Let's make the `MagicXattrRAIIWrapper` class inherit from `SingleCopy`. That makes copy assignment and copy construction private.
  - Let's change `MagicXattrManager::Get` to a void method `MagicXattrManager::GetIntoWrapper` that takes as a last parameter a pointer to a `MagicXattrRAIIWrapper` and fills its members.  For that to work, `MagicXattrManager` needs to be a friend of `MagicXattrRAIIWrapper`.

Thinking one more time about it, perhaps it's nicer to do like this:
  - We still let`MagicXattrRAIIWrapper` inherit from `SingleCopy`
  - We introduce an additional `MagicXattrRAIIWrapper` constructor that takes a `BaseMagicXattr *` with the understanding that the argument needs to be in a locked state
  - We add `BaseMagicXattr *MagicXattrRAIIWrapper::Move()`

This way we can return a  `BaseMagicXattr *` from `MagicXattrManager::Get()` and use it to construct an `MagicXattrRAIIWrapper` in `cvmfs_getxattr`.

**Comment by FanFansfan** [comment]
done.

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Review by jblomer — CHANGES_REQUESTED** [review]
Many thanks for the update!  Please also adjust the unit tests accordingly.  You can build the unit tests with `cmake -DBUILD_UNITTESTS=yes`

**Comment by FanFansfan** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Comment by jblomer** [comment]
Many thanks!  I'll carry on with small adustments in #2739

**Pull request closed without merging**
