### PR TITLE
Restrict error handling of readahead

### PR DESCRIPTION
**Pull request by HereThereBeDragons**
Issue #3299 

Instead of just removing `kLogSyslogWarn`, i think it is better to ignore errors due to not supported file type but have a hard failure if the readahead() fails due to `EBADF  fd is not a valid file descriptor or is not open for reading.`

Man page says the on error only errnos set are either `EBADF` and `EINVAL`

### CODE REVIEW

**Review by jblomer — APPROVED** [review]

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
cannot reproduce the failure of `Testing Warn on high inode watermark (Thu Jul  6 10:39:16 CEST 2023 / test number 043)`  in cloud test https://lcgapp-services.cern.ch/cvmfs-jenkins/job/CvmfsCloudTesting/1749/ . for me with ubunutu 22 it's successful

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by HereThereBeDragons** [comment]
@cernvm-bot cloudtest

**Review by vvolkl — APPROVED** [review]

**Pull request merged**
