### PR TITLE
Avoid possible race in mount helper

### LINKED ISSUE #3471: mount.cvmfs intermittent hang
`ended` needs to be checked in the while() condition
https://github.com/cvmfs/cvmfs/blob/4a477cc8eae9ffe9f6570d027b312781c7fb8001/mount/mount.cvmfs.cc#L698
without this there can be a race with the output of the child cvmfs2 which leaves mount.cvmfs stuc k in the while() loop.

### PR DESCRIPTION
**Pull request by vvolkl**
Fixes #3471

### CODE REVIEW

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
Is it understood where exactly the race comes from?

**Review by jblomer — APPROVED** [review]
It's possible that the race is connected to the timeout in the select call. I would actually think that we don't need the timeout at all. I can't see that the change would change anything for the worse.

Perhaps let's add a comment to this code block. It is apparently tricky and has kept us busy for a while.

**Comment by vvolkl** [comment]
Agreed. Added a comment to revisit this issue in the future. I think there's also some potential to refactor and break this block up a bit.

**Pull request merged**
