### PR TITLE
Adding support for image registry proxies

### LINKED ISSUE #2892: Add support for image registry proxies
Provide the option to define a proxy for an input registry. Manifest and image download requests should be directed to the proxy for images belonging to the registry.

### PR DESCRIPTION
**Pull request by radupopescu**
Set `DUCC_<REGISTRY_NAME>_PROXY` for an input registry to direct all download requests to this proxy address.

### CODE REVIEW

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Review by jblomer — APPROVED** [review]
Great!

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Pull request merged**
