### PR TITLE
Fix conversion from PathString to string, avoid path corruption

### LINKED ISSUE #3418: Many errors, corrupted filenames with external data introduced in cvmfs-2.11.0
So far I have only been able to reproduce this at Fermilab, not at CERN, but I can quite reliably reproduce it in cvmfs-2.11.0 and 2.11.1 in less than a minute with 5 parallel processes reading from different files in one osgstorage.org repository hosted at Fermilab.  /var/log/messages shows junk binary data at the end of the filename in the error message, for example:
```
Oct 16 16:39:38 dwdosgdev cvmfs2: (uboone.osgstorage.org) failed to fetch /pnfs/fnal.gov/usr/uboone/persistent/stash/uboonebeam/beam_data/bnb_data/00/00/97/19/beamdata_00009719.rootd���#017�#013W#011 (hash: d51f473dec6608c999a8ab9b7352008bbdf9c4bd, error 9 [host returned HTTP error])
```

Debug logs show that it's not just that error message, that the file name is corrupted in operations before that.  This is an excerpt showing the file name transitioning from OK to corrupted:
```
(catalog) found entry '/pnfs/fnal.gov/usr/uboone/persistent/stash/uboonebeam/beam_data/bnb_data/00/00/97/19/beamdata_00009719.root' in catalog '/pnfs/fnal.gov/usr/uboone/persistent/stash/uboonebeam/beam_data'    [10-16-2023 16:39:33 CDT]
(lru) insert md5 --> dirent: 8f613e69a813b4d3c6e69ce618edcb1c -> 'beamdata_0000919.root'    [10-16-2023 16:39:33 CDT]
(cvmfs) cvmfs_open on inode: 124280    [10-16-2023 16:39:33 CDT]
(lru) lookup inode --> path: 124280 (hit)    [10-16-2023 16:39:33 CDT]
(lru) lookup inode --> dirent: 124280 (hit)    [10-16-2023 16:39:33 CDT]
(cache) miss ./d5/1f473dec6608c999a8ab9b7352008bbdf9c4bd (-2)    [10-16-2023 16:39:33 CDT]
(cache) miss ./d5/1f473dec6608c999a8ab9b7352008bbdf9c4bd (-2)    [10-16-2023 16:39:33 CDT]
(cache) downloading /pnfs/fnal.gov/usr/uboone/persistent/stash/uboonebeam/beam_data/bnb_data/00/00/97/19/beamdata_00009719.rootd<93><FF><FF>^O<D3>^KW       [10-16-2023 16:39:33 CDT]
```

I can reproduce the problem in the July 12 nightly build but not July 8, so I'm quite confident that the problem was introduced in #3263.  CVMFS_STREAMING_CACHE is not set.

### PR DESCRIPTION
**Pull request by DrDaveD**
- Fixes #3418

Corrects bug introduced in #3263.

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Comment by jblomer** [comment]
@cernvm-bot tidy

**Review by jblomer — APPROVED** [review]
Many thanks! We have an important patch release scheduled for today, but we'll release a 2.11.2 one shortly.

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@mharvey-jt this is probably important for you. We'll release 2.11.2 with this fix shortly but in the meantime you may want to merge this in a private patch release.

**Comment by DrDaveD** [comment]
I intended for this to go into branch cvmfs-2.11.  Editing the PR...

**Pull request merged**
