### PR TITLE
Create t_smalloc.cc

### PR DESCRIPTION
**Pull request by SG345**
Unit Tests for smalloc.h

### CODE REVIEW

**Comment by jblomer** [comment]
Thanks!  Have you tried to compile and run it?  You can compile the unit tests using `cmake -DBUILD_UNITTESTS=yes` and the you can run `test/unittests/cvmfs_unittests --gtest_filter='*alloc'`.

**Comment by SG345** [comment]
Hi,
I tried to follow these steps:
1. I cloned the repository on my local machine and added the new test file.
2. I used the above cmake command to build it and received this warning: "Manually-specified variables were not used by the project:   BUILD_UNITTESTS".
3. Not sure how to run using this command "test/unittests/cvmfs_unittests --gtest_filter='*alloc'". 

However, when I tried to run the tests without using the parameters mentioned above, it passed the tests. 

Thanks!

**Comment by SG345** [comment]
I mean that I could run t_smalloc.cc manually and it passed the tests. However, I'm not sure about using the parameters above.

Thanks!

**Comment by jblomer** [comment]
Please have a close look again at the cvmfs build system and the google test output.  Checkout the cmake documentation and the CMakeLists.txt file.  At the moment, your unit test is not compiling.

**Comment by SG345** [comment]
I have fixed the compilation errors. After a bit of research, I also found that EXPECT() is usually better candidate than ASSERT() for unit tests as it leads to non-fatal failures. Please have a look at the updated file and let me know if any changes are required.

Thank you :)

**Pull request closed without merging**
