### PR TITLE
Add option to create catalog during ingestion.

### PR DESCRIPTION
**Pull request by siscia**
This pull request add a flag (-c, short for --catalog) that allow to
automagically add a (sub-)catalog when ingesting a tar file.
The catalog is added in the base dir, where the tar is "uncompressed".

I am not so sure about this implementation.
It is not a very clean design, we borrow a method from a nice interface
(AddCatalogMarker from CatalogBalancer), similarly when we are actually
adding the catalog (in SyncMediator::Commit) we are basically repeating
what is happening inside the CatalogBalancer.

However I believe that the implementation is quite reasonable and strike
a balance between functionality added and extremelly clean design.

### CODE REVIEW

**Comment by DrDaveD** [comment]
FYI a PR owner can relaunch travis by closing & reopening the PR.

**Comment by siscia** [comment]
@jblomer This features would be quite useful for unpacked.cern.ch

Do you see any problem in this PR?

**Comment by jblomer** [comment]
I'm wondering, since the tarball union engine anyway works with virtual files, wouldn't it be simpler to pretend there was a .cvmfscatalog file and let the other parts of cvmfs do the rest?

**Comment by siscia** [comment]
It seems a little bit like a hack.

I don't dislike the idea, though.

I will try to sketch an implementation and see how far we can go, it may actually work.

**Comment by jblomer** [comment]
Replaced by #2227

**Pull request closed without merging**
