### PR TITLE
Add missing install() block for cvmfs_receiver_debug

### PR DESCRIPTION
**Pull request by mcb30**
Signed-off-by: Michael Brown <mbrown@fensystems.co.uk>

### CODE REVIEW

**Comment by jblomer** [comment]
Many thanks for the patch!  This addresses [https://sft.its.cern.ch/jira/browse/CVM-1988](https://sft.its.cern.ch/jira/browse/CVM-1988)

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Review by jblomer — APPROVED** [review]

**Review by jblomer — CHANGES_REQUESTED** [review]
I approved to early.  I realized that with this change, also the RPM spec file and the debian package sources should be updated as well

**Comment by mcb30** [comment]
> I approved to early. I realized that with this change, also the RPM spec file and the debian package sources should be updated as well

Pushed two further commits (untested) to update the spec file and Debian package

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Pull request merged**
