### PR TITLE
Make "inspecting catalog" check message verbose

### PR DESCRIPTION
**Pull request by DrDaveD**
This is idea 5 from [CVM-1524](https://sft.its.cern.ch/jira/browse/CVM-1524).

### CODE REVIEW

**Review by jblomer — CHANGES_REQUESTED** [review]
Looks good to me for the `check -a` use case.  For an interactive check, the `[inspecting catalog]` messages are still useful to indicate progress.  We can add a `-l <log level>` parameter to the `cvmfs_swissknife check` invocation for the interactive case.

**Comment by DrDaveD** [comment]
But the verbose level is used to print ["[path]"](https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/swissknife_check.cc#L341) too.  

If I could separate those two messages to different log levels, I could add a default -l setting by setting CVMFS_LOG_LEVEL if it is not already set to something else, only when invoking __do_check when there's no -a option.  What kLog level should I use for "[inspecting]", what level for "[path]", and what are the -l numbers corresponding to them?

**Comment by jblomer** [comment]
Good point! The messages for [path] would then also need to be lowered to [`kLogLevel0`](https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/logging_internal.h#L63)

**Comment by DrDaveD** [comment]
I can't get that to work.  If I put in just `kLogLevel0` the message never comes out with any setting of CVMFS_LOG_LEVEL 0 to 3.  If I make it look like the definition of kLogVerboseMsg, that is, `kLogStdout | kLogShowSource | kLogLevel0` then it behaves just like kLogVerboseMsg, in that it is printed with any value of CVMFS_LOG_LEVEL.  Based on the implementation of '-l' I would expect kLogLevel0 to be a lower level than verbose, not higher, but it isn't behaving at all as I expect it.

**Comment by jblomer** [comment]
Sorry, my bad!  The `kLogLevel0` is actually not itself a log level, it is used only as a lower marker.  We need to introduce an additional log level.  I'd suggest to add in `logging_internal.h` an additional level, e.g. `kLogGossipy` (feel free to pick a better name), and to shift all following constants by a factor of two.

**Comment by DrDaveD** [comment]
Ok, I ended up having to do quite a lot for that.  The '-l' options to swissknife were broken, trying to shift the number 1 by a mask level (a power of 2) rather than a number of bits.  I added a kLogInfoMsg alias (with mask kLogInform) between the kLogWarning (kLogNormal) and kLogVerboseMsg (kLogVerbose) levels.  I reversed the order so the log levels increase as people expect, where level 1 corresponds to Warning/Normal, level 2 is Info, and level 3 is Verbose.  I removed kLogDiscrete because it was only used during one test to turn off all log levels, and kLogLevel0 does that now.

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by jblomer** [comment]
@cernvm-bot tidy

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Comment by DrDaveD** [comment]
The failures seem unrelated to me.  Maybe run them again?

**Comment by jblomer** [comment]
There is just one more issue: the messages are now formatted like

    (cvmfs) [inspecting catalog ...

This is because `kLogShowSource` is used.  I guess the code should use `kLogStdout | kLogVerbose` instead of `kLogVerboseMsg`.

**Comment by DrDaveD** [comment]
I don't think that extra (cvmfs) hurts but anyway I changed it to `kLogStdout | kLogInform`, as ugly as that is.

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Comment by jblomer** [comment]
@cernvm-bot tidy

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Review by jblomer — APPROVED** [review]

**Pull request merged**
