### PR TITLE
Reload geodb after a new one is downloaded

### PR DESCRIPTION
**Pull request by DrDaveD**
See [CVM-1739](https://sft.its.cern.ch/jira/browse/CVM-1739).

Also move stratum1 used in the service test back from unl to fnal.

### CODE REVIEW

**Comment by jblomer** [comment]
@DrDaveD Thanks, Dave!  Please let me know whether the unit test failure is understood.

**Comment by DrDaveD** [comment]
Don't merge the current version even though it will probably pass tests; it doesn't work with the second reopen DB

**Comment by DrDaveD** [comment]
Ok this version works. 

Should I get rid of the cvmfs_globals.CVMFS_UNITTESTS and cvmfs_globals.py now?  I don't know if anything else is expecting it.

**Comment by DrDaveD** [comment]
I did a build after removing the python cvmfs_globals and nothing complained about them being missing, and it passed the 614-geoservice test, so I added the commit to this PR.

**Comment by DrDaveD** [comment]
This one should be ready to go.

**Comment by jblomer** [comment]
Ah, I forgot to double check, this went into the devel branch.  Could you please reopen against the 2.6 branch?

**Pull request merged**
