### PR TITLE
Fix tests on yubikey-test node, which was migrated to alma9

### PR DESCRIPTION
**Pull request by vvolkl**

### CODE REVIEW

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Review by jblomer — APPROVED** [review]

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
Yubikey test is fixed, one test likely flakey.

**Pull request merged**
