### PR TITLE
CommitProcessor: add intermediary root catalog to reflog

### PR DESCRIPTION
**Pull request by janpriessnitz**
New (intermediary) root catalog should also be added to reflog,
so the catalog tree can be garbage collected as well.

### CODE REVIEW

**Comment by janpriessnitz** [comment]
The additional root catalog hash is added to reflog through signing tool, which is not very clean. I tried creating a separate function which will add catalog to reflog, but it needs to initialize a LOT of stuff just to update the reflog and would result in 200+ additional lines of code. Is there a better way?

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest nodestroy

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest nodestroy

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest

**Comment by janpriessnitz** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@janpriessnitz Looks good to me!  Please rebase.

**Comment by janpriessnitz** [comment]
@jblomer good to go

**Pull request merged**
