### PR TITLE
FIX: Hardlink Check and Preprocessing in OverlayFS

### PR DESCRIPTION
**Pull request by reneme**
This fixes a problem with hardlink handling in OverlayFS where certain `SyncItem`s where skipped due to the *silent* creation of `SyncItem` objects inside `SyncMediator`.

*Note:* This depends on the pull request [Refactor: SyncItem Factory Method](https://github.com/cvmfs/cvmfs/pull/1149).

### CODE REVIEW

**Comment by jblomer** [comment]
I was about to merge, currently stuck on a compile error:

    sync_union.cc:227: error: 'CAP_IS_SUPPORTED' was not declared in this scope

I think this came from a previous pull request.  Probably only defined on newer Linuxes.

**Comment by jblomer** [comment]
One more thing: before merging, please check the conflict situation with CVM-908

**Comment by reneme** [comment]
> Probably only defined on newer Linuxes.

Which version did you compile on?

**Comment by jblomer** [comment]
SL6

**Comment by reneme** [comment]
Opened a [new pull request](https://github.com/cvmfs/cvmfs/pull/1156) on top of this one to fix that `CAP_IS_SUPPORTED()` is *not* supported everywhere. Yuk!

**Pull request merged**
