### PR TITLE
Feature: CernVM-FS Server logs Events to Syslog

### PR DESCRIPTION
**Pull request by reneme**
**Note:** This pull request will be amended with more messages. Opening it early to allow for discussion.

This adds several syslog messages for common CernVM-FS server actions as requested in [CVM-812](https://sft.its.cern.ch/jira/browse/CVM-812) and [CVM-861](https://sft.its.cern.ch/jira/browse/CVM-861).

### CODE REVIEW

**Comment by jblomer** [comment]
Looks fine to me!

**Comment by reneme** [comment]
Mhh, I think I'll move more of the status messages to the `cvmfs_server` script. This allows me to *always* print something like "publish failed" even if a random assertion fired.

**Comment by reneme** [comment]
... details *what* went wrong should be in user-defined logs anyways.

**Comment by jblomer** [comment]
Just in case you don't already know, in the shell there would be `logger` to write to syslog.

**Comment by reneme** [comment]
Details:
`cvmfs_server` now posts common server events to the syslog. For a detailed list of logged messages please refer to [CVM-812](https://sft.its.cern.ch/jira/browse/CVM-812). Furthermore this pull request contains some refactorings to facilitate the logging.

Namely, I wrapped calls to `cvmfs_swissknife info` into `get_repo_info()` that now also conveniently hides the call to `get_follow_http_redirects_flag()`. And `cvmfs_server snapshot` has a new error handler `__snapshot_failed()` to distinguish between success and failure.

**Comment by jblomer** [comment]
Is it ready to be merged from your side?

**Comment by reneme** [comment]
one more thing... 5'

**Comment by reneme** [comment]
Should be ready now... just cosmetics. This is screaming for an integration test run, though. :-)

**Comment by reneme** [comment]
updated with [Steve's suggestion](https://sft.its.cern.ch/jira/browse/CVM-812?focusedCommentId=72250&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-72250) for parsability.

**Pull request merged**
