### PR TITLE
Release transaction lock after template transaction failure

### PR DESCRIPTION
**Pull request by aandvalenzuela**

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
@cernvm-bot cloudtest

**Comment by aandvalenzuela** [comment]
@cernvm-bot cloudtest

**Comment by aandvalenzuela** [comment]
@cernvm-bot cloudtest cc7

**Comment by aandvalenzuela** [comment]
@cernvm-bot cloudtest

**Review by jblomer — APPROVED** [review]

**Pull request merged**
