### PR TITLE
Update cvmfs-config-default for a config-repo based configuration

### PR DESCRIPTION
**Pull request by DrDaveD**
As discussed in [CVM-1085](https://sft.its.cern.ch/jira/browse/CVM-1085).  The corresponding configuration repository is the [default branch of cvmfs-contrib/config-repo](https://github.com/cvmfs-contrib/config-repo/tree/default).  I tested it by putting that contents into my own test repository, then setting CVMFS_CONFIG_REPOSITORY to point to it in a `/etc/cvmfs/default.d/95-dwd.conf.`  The configuration repository contents will need to be published before this is released.

I have seen one problem with this on Debian, in that when I upgrade from the current version of cvmfs-config-default to this version, it does not remove the files under /etc/cvmfs that got removed even though they hadn't been modified.  I don't know if that's just my test machine, something in the package definition, or what.  That will need further investigation before this is merged but I wanted to get it started being reviewed, and maybe someone else knows the answer to this problem.

### CODE REVIEW

**Comment by DrDaveD** [comment]
Ok I think I figured out the right way to remove the old configuration files.  It still warns about removing the empty directories before removing the files, and then doesn't remove the directory, but it appears to be a dpkg bug and it doesn't cause any harm.
```
Preparing to unpack .../cvmfs-config-default_1.9_all.deb ...
Unpacking cvmfs-config-default (1.9) over (1.8-1) ...
dpkg: warning: unable to delete old directory '/etc/cvmfs/domain.d': Directory not empty
dpkg: warning: unable to delete old directory '/etc/cvmfs/keys/opensciencegrid.org': Directory not empty
dpkg: warning: unable to delete old directory '/etc/cvmfs/keys/egi.eu': Directory not empty
Setting up cvmfs-config-default (1.9) ...
Removing obsolete conffile /etc/cvmfs/config.d/grid.cern.ch.conf ...
Removing obsolete conffile /etc/cvmfs/config.d/cms.cern.ch.conf ...
Removing obsolete conffile /etc/cvmfs/default.d/60-egi.conf ...
Removing obsolete conffile /etc/cvmfs/default.d/50-cern-debian.conf ...
Removing obsolete conffile /etc/cvmfs/domain.d/egi.eu.conf ...
Removing obsolete conffile /etc/cvmfs/domain.d/cern.ch.conf ...
Removing obsolete conffile /etc/cvmfs/domain.d/opensciencegrid.org.conf ...
Removing obsolete conffile /etc/cvmfs/keys/opensciencegrid.org/opensciencegrid.org.pub ...
Removing obsolete conffile /etc/cvmfs/keys/egi.eu/egi.eu.pub ...
```

**Comment by DrDaveD** [comment]
@jblomer Can you take a look at this?

**Comment by jblomer** [comment]
Absolutely!  Many thanks for starting the work on this.  I'll get to it next week.

**Comment by jblomer** [comment]
Replaced by #2586

**Pull request closed without merging**
