### PR TITLE
Convert geoip database to GeoLite2

### PR DESCRIPTION
**Pull request by DrDaveD**
See [CVM-1496](https://sft.its.cern.ch/jira/browse/CVM-1496)

### CODE REVIEW

**Comment by jblomer** [comment]
Many thanks!

I ran a build on all the platforms.  It turns out that there is a missing build dependency on `python-setuputils` and, for deb packages, on `cpio`.  The new MaxMind module doesn't build anymore on SL5.  I'd suggest to add a CMake option to switch off building the Geo-API (which should default to "on") and to optionally exclude it in the cvmfs-universal.spec file.

**Comment by DrDaveD** [comment]
Ok @jblomer I made the changes you requested, and also rebased it against the current cvmfs-2.5 branch.  Please try the all-platform build again.

**Comment by DrDaveD** [comment]
I think I fixed everything you noticed.  The debian problem was not with the missing maxminddb.h; it intentionally tries that compile and continues without it if it fails.  The problem was that there was a lib.linux-i686-2.7 directory instead of a lib directory.  I changed it to use lib*.

If this doesn't fix everything, feel free to fix it yourself either by updating this PR or merging it and making a new one, instead of waiting for me and getting into multiple 24 hour cycles.

**Comment by jblomer** [comment]
I didn't come to look into it today. Can you see the results on this page:
https://epsft-jenkins.cern.ch/view/CVMFS/job/CvmfsFullBuildDocker/786/

Perhaps it's fastest if you could test build in a local docker container, e.g. on Fedora 27 and Ubuntu 18.04.

**Comment by DrDaveD** [comment]
Ok I built in an f27 docker container and on my debian 9 machine, please try on Jenkins again.

**Pull request merged**
