### PR TITLE
Skip AFS in cvmfs_config fuser

### LINKED ISSUE #3090: cvmfs_config fuser runs too long on host with afs
On a system in Wisconsin that uses AFS, the `lsof` command run by `cvmfs_config fuser` takes forever to run and strace showed it doing lots of things under `/afs`.   We found that adding the `-e /afs` option made the lsof instead complete in 30 seconds, on a system that had 159 users.  The option fails with an error if `/afs` is not mounted, so first check to see if it is there before adding the option.

### PR DESCRIPTION
**Pull request by jblomer**
Fixes #3090

### CODE REVIEW

**Comment by cvuosalo** [comment]
I tested this change on a node where the original version of `cvmfs_config fuser` runs very long, and I confirmed that the change in this merge request allows `cvmfs_config` to complete quickly as it should.

**Comment by jblomer** [comment]
Great, thanks for testing!  I'll merge it then and backport it to the 2.10 branch.

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Pull request merged**
