### PR TITLE
Manage case when we don't find the server.conf configuratio file.

### PR DESCRIPTION
**Pull request by siscia**
I tried to address the issue of that Valetin brought up today.

I am definitely not sure if this is enough.

### CODE REVIEW

**Comment by jblomer** [comment]
LGTM

**Comment by siscia** [comment]
Still looks quite ugly...

```
$ cvmfs_server transaction bar.ch
(unexpected termination) Unable to find the configuration file `server.conf` for the cvmfs publisher

Stacktrace:
cvmfs_publish(+0x379c7) [0x563ae04049c7]
cvmfs_publish(+0x307a3) [0x563ae03fd7a3]
cvmfs_publish(+0x39e81) [0x563ae0406e81]
cvmfs_publish(+0x348a9) [0x563ae04018a9]
cvmfs_publish(+0x124dc) [0x563ae03df4dc]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7ff9975eab97]
cvmfs_publish(_start+0x2a) [0x563ae03df5da]
```

**Comment by jblomer** [comment]
Already better than before :)
For a nicer output, we should give this issue a well-defined error code and catch the exception in the transaction command. Like here: https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/publish/cmd_transaction.cc#L77

**Comment by siscia** [comment]
I don't like this at all. 

We are coupling how we get the repository name in `CreateSettingsPublisher` and in `CmdTransaction` that feels very wrong. Moreover we are making the  method `GetSingleAlias` public. That feels somehow wrong.

Maybe it is better to leave just the thrown of the exceptions.

**Comment by siscia** [comment]
Alright, I like this version much better.

The methods are private again, and everything seems to flow quite nicely.

However it costed us the fact that I started a hierarchy of errors, and we kinda agree that it is not ideal. However in this case it seems as the most sensible strategy... Thoughts?

**Comment by siscia** [comment]
@jblomer I would have liked to return the UniquePtr directly, but I wasn't able to do so.

**Pull request merged**
