### PR TITLE
Keep file type in inode tracker

### LINKED ISSUE #2834: EIO when entry changes file type
Hi,

If an entry on a cvmfs file system changes file type (eg from a symlink to a directory), this can cause kernel to emit an EIO on a stat() / getattr() operation. This arises in 
 `fs/fuse/dir.c` at https://github.com/torvalds/linux/blob/bc491fb12513e79702c6f936c838f792b5389129/fs/fuse/dir.c#L1003 .
The cause of this is that CVMFS preserves inode numbers across a catalog reload, but doesn't account for the possibility of changing type. This means that the kernel can see an inode file type changing between successive lookup/getattr operations. This, apparently, breaks a fundamental assumption in the kernel https://www.spinics.net/lists/linux-fsdevel/msg190819.html  .
This can be mitigated by globally disabling kernel caching with `CVMFS_KCACHE_TIMEOUT=0` or by setting the specific inode's entry timeout to zero.

The `EIO` only happens once. That causes the kernel to invalide the inode, and a fuse `forget` is sent to CVMFS. This drops the cached inode entry and the next operation on the entry causes a new path->inode lookup resulting in a new inode number.

I'm not actually sure if there's a general solution to this that won't push a race elsewhere. Our specific scenario is the conversion of a symlink (that points to an off-cvmfs directory) into a directory of the same name.

Steps to repro:
1) Set up a repro publishing loop that changes an entry from a directory to a symlink on alternate publications. Make the repo TTL 1sec.
2) Mount the repo on a client and do a tight loop lstat()ing that entry, noting `errno`. - EIOs should quickly appear.

### PR DESCRIPTION
**Pull request by jblomer**
Detects the issue described in #2834

### CODE REVIEW

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by radupopescu** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
... looking into the 076 test failure

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Comment by jblomer** [comment]
@cernvm-bot cloudtest

**Pull request merged**
