### PR TITLE
change default graft size from 32 to 24 MB

### PR DESCRIPTION
**Pull request by DrDaveD**
See [CVM-1291](https://sft.its.cern.ch/jira/browse/CVM-1291)

### CODE REVIEW

**Comment by jblomer** [comment]
Many thanks!

I think it would be good to introduce a private constant like `kDefaultChunkSize` for the `CommandGraft` class so that the number only needs to be changed at one place.

**Comment by DrDaveD** [comment]
Ok, I pushed an update, but since I need to use a string it isn't quite as clean as an integer constant.   C++03 does not allow setting a per-class static constant string that is initialized at the same time as it is defined.  Instead I have to define it in the class definition but initialize it in swissknife_graft.cc.   I can initialize an integer when it is defined, but GetDescription() wants a string.  C++11 has a new 'constexpr' way to assign strings the same time as they're defined, but we're not using C++11.

**Comment by jblomer** [comment]
You can use an `unsigned` constant and the `StringifyUint` helper from util/string.h

**Comment by DrDaveD** [comment]
Ok how about now

**Pull request merged**
