### PR TITLE
Tracer implementation

### PR DESCRIPTION
**Pull request by samysweb**
**Note: This pull request should only be considered once #2151 is merged**

This pull request contains the implementation of a tracer which allows the tracing of the following file system operations:
- `opendir` and `open`
- `lookup`
- `statfs` and `getattr`
- `listxattr` and `getxattr`
- `readlink`

The tracer was implemented in a way that should minimize the overhead when the tracer is deactivated and used the base implementation already available in `tracer.cc`.

An integration test was added to check the functionality described above.

The tracer can be activated by defining `CVMFS_TRACEFILE` in the configuration file.
Additionally `CVMFS_TRACEBUFFER` (size of the tracebuffer) and `CVMFS_TRACEBUFFER_THRESHOLD` (threshold for a tracebuffer flush) can be defined to further customize the behaviour of the tracer.

### CODE REVIEW

**Comment by samysweb** [comment]
Given the trace log [cvmfs-atlas.cern.ch.trace.log](https://github.com/cvmfs/cvmfs/files/2158250/cvmfs-atlas.cern.ch.trace.log) the converter produces the spec file [cvmfs-atlas.cern.ch-3.trace.spec.txt](https://github.com/cvmfs/cvmfs/files/2158251/cvmfs-atlas.cern.ch-3.trace.spec.txt)

**Comment by jblomer** [comment]
Very nice!
For the first three entries

    ^/repo/ATLASLocalRootBase/config/localFrontierSquid.sh
    ^/repo/ATLASLocalRootBase/config/localPostUserSetup.sh
    ^/repo/ATLASLocalRootBase/etc/*

Can you remind me why the first two are not collapsed into `^/repo/ATLASLocalRootBase/config/*`?

**Comment by samysweb** [comment]
I also added a small python script which checks if a given spec file contains all files that were called during a logged execution. I don't know if we actually need this one (I mainly added it for testing purposes)

**Comment by jblomer** [comment]
The PR somehow still seems to show the changes from the previous, merged one. Can you try rebasing to the latest devel?

**Comment by samysweb** [comment]
Will create new, clean pull request...

**Pull request closed without merging**
