### PR TITLE
CVM-1927 dir to symlink unittests

### PR DESCRIPTION
**Pull request by siscia**
Reproduce CVM-1927 with unittests.

### CODE REVIEW

**Comment by siscia** [comment]
@cernvm-bot cloudtest cc7

**Comment by siscia** [comment]
I expect this PR to pass all the test. I believe this is ready to review / merge.

**Comment by siscia** [comment]
@cernvm-bot cloudtest cc7

**Comment by siscia** [comment]
@jblomer

**Comment by siscia** [comment]
@cernvm-bot cloudtest

**Review by jblomer — APPROVED** [review]
Looks good to me!  Tricky catch.

**Pull request merged**
